parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  browser: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
extends: standard
rules:
  semi: ['error', 'always']
  comma-dangle: ['error', 'only-multiline']
  indent: ['error', 4]
  space-before-function-paren: ['error', 'never']

  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error

  no-useless-constructor: off
  '@typescript-eslint/no-useless-constructor':
    - error
